config/routes.rb
BlueRegister::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "home/index"

  namespace :api do
    namespace :blue_button do
      resources :apps, :only => :index
      resource :registry, :only => :show
      resources :providers, :only => :index
      resources :json_web_keys, :only => :index
    end
  end

  resources :apps
  resources :registry
  resources :providers

  match "/generated/public_jwks" => "api/blue_button/json_web_keys#index", :as => "blue_button_public_keys"
  match "/.well-known/bb/registry" => "api/blue_button/registries#show", :as => "blue_button_registry"

  [:app, :provider].each do |resource|
    match "/.well-known/bb/#{resource}" => "api/blue_button/#{resource.to_s.pluralize}#index", :as => "blue_button_#{resource}"
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
:javascript
  $(function(){
    mixpanel.track('Home');
    mixpanel.track_links('.jumbotron .btn', 'Signup Clicked');
  })
%hr/
.jumbotron
  %h1 Join BlueButton+
  %p.lead Register provider and application endpoints for BlueButton+ Push. Join the next generation of healthcare.
  %p
    != [:provider, :app].collect{|r| link_to(pluralize(r.to_s.classify.constantize.count, r.to_s), send("blue_button_#{r}_path", format: :json)) }.to_sentence
    registered so far
  %p Our discovery endpoint is located at #{link_to blue_button_registry_path(format: :json), blue_button_registry_path(format: :json)}
  .btn-group
    %a.btn.btn-large.btn-success.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
      Register My
      &nbsp;
      %span.caret
    %ul.dropdown-menu
      %li
        %a{href: new_provider_path } Provider
      %li
        %a{href: new_app_path } Application
%hr/
.row-fluid.marketing
  .span6
    %h4 Get involved
    %p You can be an advocate within your organization to implement BB+. <a href='#TODO'>Find out how</a>.
    %h4 Is BB+ right for me?
    %p If you're a healthcare provider, payer, or deal with PHI, then you're in the right place. MU stage 2 is coming and you need to be prepared. Implenting a BB+ CCDA portal is the easiest way to get V/D/T, and is a good bet to stay on top of MU stage 3. <a href='#TODO'>Learn more</a>
    %h4 Subheading
    %p Maecenas sed diam eget risus varius blandit sit amet non magna.
  .span6
    %h4 Looking for a BB+ registry?
    %p You've come to the right place. Using our registry is free and easy, look at the <a href="#TODO"> developer guide</a> to get started.
    %h4 Subheading
    %p Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.
    %h4 Subheading
    %p Maecenas sed diam eget risus varius blandit sit amet non magna.
%hr/